config/routes.rb
Sirihumor::Application.routes.draw do
  resources :posts, :only => [:index, :create, :new, :show]
  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_validation :parse_message, :on => :create
  attr_accessor :message
  mount_uploader :screenshot, ScreenshotUploader
  validates :screenshot, :presence => true

  scope :active_posts, where(:active => true)

  private
  def parse_message
    if message
      self.screenshot = message_attachment_as_file unless message.attachments.empty?
      self.from_email = message.from
    end
  end

  def message_attachment_as_file
    attachment = message.attachments.first
    file = StringIO.new(attachment.decoded)
    file.class.class_eval { attr_accessor :original_filename, :content_type }
    file.original_filename = attachment.filename
    file.content_type = attachment.mime_type

    file
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'mail'
  respond_to :html

  def index
    @posts = Post.active_posts.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  # called by cloudmailin
  def create
    if params[:message]
      create_from_email
    else
      create_from_form
    end
  end

  private
  def create_from_email
    message = Mail.new(params[:message])
    @post = Post.new(:active => true, :message => message)

    if @post.save
      ThankYouMailer.success(@post.from_email).deliver
    else
      ThankYouMailer.failure(@post.from_email, @post.errors.full_messages.join('. ') << '.').deliver
    end

    render :nothing => true, :status => 200
  end

  def create_from_form
    @post = Post.new(params[:post])
    @post.save
    respond_with @post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def iphone_user_agent?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(Mobile\/.+Safari)/]
  end
end

app/views/layouts/_topbar.html.haml
.topbar
  .topbar-inner
    .container
      %h1.icon
        = link_to "SiriHumor.me", root_url, :class => :icon
      = render_navigation

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "Siri Humor - Funny things Siri says"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name => "keywords", :content => "Siri, Humor, Funny"}
    
  %body
    = render :partial => 'layouts/topbar'
            
    .container
      #content= yield
      .push

    %footer
      %h2 
        Email your own screenshots as an attachment to 
        = mail_to Settings.attachment_email
      

app/views/pages/faq.html.haml
.faq 
  %h3 How do I take screenshot on my iPhone? 
  %h4 Simultaneously hold down the Home and Sleep/Wake buttons, then release them together.

  %h3 Is there another way to submit my screenshots?
  %h4 
    Yes. Email the screenshot as an attachment to 
    = mail_to Settings.attachment_email
    %span.dot .

  %h3 May I post any screenshot I like?
  %h4 Please post only iPhone screenshots of Siri conversations. Keep it clean!

app/views/posts/_email_instructions.html.haml
%ol.email-instructions
  %li To take a screenshot on your iPhone, simultaneously hold down the Home and Sleep/Wake buttons, then release them together.
  %li 
    Email the screenshot as an attachment to 
    = mail_to Settings.attachment_email
    %span.dot .

app/views/posts/_form.html.haml
.form
  = form_for @post, :html => {:multipart => true} do |f|
    %fieldset
      %legend Submit Your Own Siri Screenshot
      - unless @post.errors.empty?
        .alert-message.error.fade.in{'data-alert' => 'alert'}
          %a.close{:href => '#'} x
          %p= (@post.errors.full_messages.join('. ') << '.')
      
      .clearfix
        = f.label :screenshot
        .input= f.file_field :screenshot, :class => 'input-file'
        = f.hidden_field :screenshot_cache
        = f.hidden_field :active, :value => true
      .actions
        = f.submit "Save", :class => 'btn primary'
        = link_to('Cancel', root_url, :class => 'btn')

  %h4 
    You can also email the screenshot as an attachment to 
    = mail_to Settings.attachment_email
    %span.dot .

app/views/posts/index.html.haml
- for post in @posts
  = image_tag post.screenshot.url, :class => 'screenshot', 'data-id' => post.id

app/views/posts/new.html.haml
- if iphone_user_agent?
  = render :partial => 'email_instructions'
- else
  = render :partial => 'form'

app/views/posts/show.html.haml
.show
  %h2 Well done! You successfully uploaded your Siri screenshot.
  %h3 
    Now you can
    = link_to('add another', new_post_url)
    or
    = link_to('go back', root_url)
    %span.dot .

    